# input data
base_dir: /home/bsplab/Documents/3dv/3DV-2022/assignment
data_dir: ${base_dir}/data/chair
dtype: "mesh" # "point" "voxel"
n_points: 2048

# vision model
arch: resnet18

# training
lr: 0.0004
max_iter: 10000

# dataloader
batch_size: 10
num_workers: 2

# logger
log_freq: 1000

# checkpoint
save_freq: 100
load_checkpoint: False

# eval
vis_freq: 100
load_eval_checkpoint: True

w_chamfer: 1.0
w_smooth: 0.1
w_edge: 1.0
w_normal: 0.01